### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by AdfPizarro**
Add test suit for

Creating a new project
Error on creating and empty name project

Creating a new task
Deleting a task
Updating the task status (complete, pending)
Edit a task
Error task with empty fields
Change task priority

### CODE REVIEW

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @AdfPizarro and @jpdf00  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the requirements so carefully, keep it up, and your project is really almost done.
:+1: I liked also how your codes are clean. Keep up the good job!
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Make sure that you test all of the functions you have from all modules, currently some of the functions from `src/projects.js`, `src/index.js`, and `src/tasks.js` are not covered by tests. kindly test them all
- [ ] Edit the readme file and specify how to run test

# [Optional changes] :yellow_circle: 
- [ ] Try to setup github actions for tests
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by jpdf00** [comment]
Hi. Thanks for your review @descholar-ceo.

Can you please point out which functions we are referring to?

I know that some functions aren't being tested but all of them are functions related to DOM manipulation, and I couldn't find any material about testing functions related to DOM manipulation.

In case you are referring to the ones that manipulate the DOM, can you please share some material about testing DOM manipulation?

**Comment by descholar-ceo** [comment]
> Hi. Thanks for your review @descholar-ceo.
> 
> Can you please point out which functions we are referring to?
> 
> I know that some functions aren't being tested but all of them are functions related to DOM manipulation, and I couldn't find any material about testing functions related to DOM manipulation.
> 
> In case you are referring to the ones that manipulate the DOM, can you please share some material about testing DOM manipulation?

Hello @jpdf00 , thank you for reaching out about more clarification, About DOM manipulation function, I would advise you to try testing them as well because it's possible, it would be of a great opportunity to practice even things that you think are difficult because this is a learning process. About the resources, try [this article](https://ms314006.github.io/unit-testing-for-dom-manipulation/)

**Review by descholar-ceo — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @AdfPizarro and @jpdf00  , your project is approved :tada: :tada: :tada: 
You have implemented all requested changes from the previous review for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Pull request merged**
